sudo: false

language: node_js
node_js:
  - 11

branches:
  only:
    - master

deploy:
  provider: heroku
  app: "raspberry-web-app-server"
  api_key:
    secure: "BLt3RfmijfjZWP2CTAga19GxDsQIqpE3uH4wXZi7jy86XUqjq/JMBl9p3VRmxrx/sD0+ekLl6GS5amC9Ty9ot4vJO+n+DzVkmf0WPpfGke/ulzRZ0DFgyFJi0RkanL4dHCV6gRbJXxxsK711aM/ZE3P/aFAXecqplGYR/+8G1+UiPcanhAikcdekKBeHCYuhrw1MDtSVZRcG2pUUjvk37sNJGBC7pJmfWqgHv8c7RZxZNtdkijDfSP2Doi1Css8BRAYP40pL5bu7udAPBoxnjBTJVxG43YF/X2Rn5NSjISC3hvFA2h0u4sIUSmynysf4bxRUr1LTilk1mJHJH030B1hAIXVH8poPFdPcxKqKNNeFOXLs2PggKJOc861nbCyrkq3ticnKrTndfOe8m8eduoR5C6LD3SDFyvxMMRf8UxNdbVu//QZohot90HrmybXLgocNNXNOiKf6fCdm5csQfy4yAC2RLvAtSjY7TiDhRQAWmLh7GOga0EZS5nSCbhcyCpWenuUAzhgMfiyR69pL7Gcl6V97exFluBeOEVS0mS758TU4K7MnignAl2CZZg2wGBR1EzgfRjceCLU5Sj/WBGHYat4Mt3YL/QGU0LnePfnqds35zIGhsl7MXkj87wLZSqx+F//AyVAuXRgoSoEcxdudWPGZhLVTus1aeRzg3/c="
